<?php

declare(strict_types=1);
require __DIR__.'/includes/auth.php';require __DIR__.'/config/database.php';require __DIR__.'/includes/functions.php';
$title='Attendance';$date=$_GET['date']??date('Y-m-d');$classId=(int)($_GET['class_id']??0);$classes=$pdo->query('SELECT id,class_name FROM classes ORDER BY class_name')->fetchAll();$students=[];$existing=[];
if($classId){$statement=$pdo->prepare('SELECT id,name,student_id FROM students WHERE class_id=? AND status="Active" ORDER BY name');$statement->execute([$classId]);$students=$statement->fetchAll();$statement=$pdo->prepare('SELECT student_id,status FROM attendance WHERE attendance_date=? AND student_id IN (SELECT id FROM students WHERE class_id=?)');$statement->execute([$date,$classId]);foreach($statement as $row)$existing[$row['student_id']]=$row['status'];}
require __DIR__.'/includes/header.php';
?>
<div class="rounded-xl bg-white p-5 shadow-sm"><form class="grid gap-4 sm:grid-cols-3 sm:items-end"><label class="text-sm font-medium">Attendance Date<input type="date" name="date" value="<?=e($date)?>" class="mt-1 w-full rounded-lg border px-3 py-2.5"></label><label class="text-sm font-medium">Class<select name="class_id" class="mt-1 w-full rounded-lg border px-3 py-2.5"><option value="">Select class</option><?php foreach($classes as $class):?><option value="<?=$class['id']?>" <?=selected($classId,$class['id'])?>><?=e($class['class_name'])?></option><?php endforeach;?></select></label><button class="rounded-lg bg-slate-800 px-4 py-2.5 text-sm font-semibold text-white">Load Students</button></form></div>
<?php if($classId):?><form method="post" action="attendance-save.php" class="mt-6 rounded-xl bg-white shadow-sm"><input type="hidden" name="attendance_date" value="<?=e($date)?>"><input type="hidden" name="class_id" value="<?=$classId?>"><?php if(!$students):?><p class="p-10 text-center text-sm text-slate-500">No active students in this class.</p><?php else:?><div class="overflow-x-auto"><table class="w-full min-w-[600px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Student</th><th class="px-5 py-3 text-center">Present</th><th class="px-5 py-3 text-center">Absent</th><th class="px-5 py-3 text-center">Leave</th></tr></thead><tbody><?php foreach($students as $student):$value=$existing[$student['id']]??'Present';?><tr class="border-t"><td class="px-5 py-4"><p class="font-medium"><?=e($student['name'])?></p><p class="text-xs text-slate-500"><?=e($student['student_id'])?></p></td><?php foreach(['Present','Absent','Leave'] as $status):?><td class="px-5 py-4 text-center"><input type="radio" name="status[<?=$student['id']?>]" value="<?=$status?>" <?=checked($value,$status)?> class="h-4 w-4 accent-green-700"></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><div class="border-t p-5"><button class="rounded-lg bg-green-700 px-5 py-2.5 text-sm font-semibold text-white">Save Attendance</button></div><?php endif;?></form><?php else:?><div class="mt-6 rounded-xl bg-white p-10 text-center text-sm text-slate-500 shadow-sm"><i class="fa-solid fa-calendar-check mb-3 text-3xl text-slate-300"></i><p>Select a date and class to begin.</p></div><?php endif;?>
<?php require __DIR__.'/includes/footer.php';?>
