<?php

declare(strict_types=1);
require __DIR__.'/includes/auth.php';require __DIR__.'/config/database.php';require __DIR__.'/includes/functions.php';
$title='Add Fee Payment';$students=$pdo->query('SELECT id,student_id,name FROM students WHERE status="Active" ORDER BY name')->fetchAll();$errors=[];$fee=['student_id'=>'','fee_month'=>date('Y-m'),'amount'=>'','paid_amount'=>'','due_amount'=>'0.00','status'=>'Due','payment_date'=>date('Y-m-d')];
if($_SERVER['REQUEST_METHOD']==='POST'){foreach($fee as $field=>$value)$fee[$field]=trim($_POST[$field]??$value);$fee['amount']=(float)$fee['amount'];$fee['paid_amount']=(float)$fee['paid_amount'];$fee['due_amount']=max(0,$fee['amount']-$fee['paid_amount']);$fee['status']=$fee['paid_amount']>=$fee['amount']&&$fee['amount']>0?'Paid':($fee['paid_amount']>0?'Partial':'Due');if(!$fee['student_id']||$fee['amount']<=0||!$fee['payment_date'])$errors[]='Student, a positive amount and payment date are required.';if($fee['paid_amount']<0||$fee['paid_amount']>$fee['amount'])$errors[]='Paid amount must be between zero and the total amount.';if(!$errors){$pdo->prepare('INSERT INTO fees(student_id,fee_month,amount,paid_amount,due_amount,status,payment_date) VALUES(?,?,?,?,?,?,?)')->execute([$fee['student_id'],$fee['fee_month'],$fee['amount'],$fee['paid_amount'],$fee['due_amount'],$fee['status'],$fee['payment_date']]);set_flash('success','Fee payment added successfully.');redirect('fees.php');}}
require __DIR__.'/includes/header.php';
?>
<?php if($errors):?><div class="mb-5 max-w-3xl rounded-lg bg-red-50 p-4 text-sm text-red-700"><?=e(implode(' ',$errors))?></div><?php endif;?><form method="post" class="max-w-3xl rounded-xl bg-white p-5 shadow-sm"><div class="grid gap-5 sm:grid-cols-2"><label class="text-sm font-medium">Student<select name="student_id" required class="mt-1 w-full rounded-lg border px-3 py-2.5"><option value="">Select student</option><?php foreach($students as $student):?><option value="<?=$student['id']?>" <?=selected($fee['student_id'],$student['id'])?>><?=e($student['name'].' ('.$student['student_id'].')')?></option><?php endforeach;?></select></label><label class="text-sm font-medium">Fee Month<input type="month" name="fee_month" value="<?=e($fee['fee_month'])?>" required class="mt-1 w-full rounded-lg border px-3 py-2.5"></label><label class="text-sm font-medium">Total Amount<input type="number" min="0" step="0.01" name="amount" value="<?=e($fee['amount'])?>" required class="mt-1 w-full rounded-lg border px-3 py-2.5"></label><label class="text-sm font-medium">Paid Amount<input type="number" min="0" step="0.01" name="paid_amount" value="<?=e($fee['paid_amount'])?>" required class="mt-1 w-full rounded-lg border px-3 py-2.5"></label><label class="text-sm font-medium">Due Amount<input name="due_amount" value="<?=e($fee['due_amount'])?>" readonly class="mt-1 w-full rounded-lg border bg-slate-50 px-3 py-2.5"></label><label class="text-sm font-medium">Status<select name="status" readonly class="mt-1 w-full rounded-lg border bg-slate-50 px-3 py-2.5"><option>Paid</option><option>Partial</option><option selected>Due</option></select></label><label class="text-sm font-medium">Payment Date<input type="date" name="payment_date" value="<?=e($fee['payment_date'])?>" required class="mt-1 w-full rounded-lg border px-3 py-2.5"></label></div><div class="mt-6 flex gap-3"><button class="rounded-lg bg-green-700 px-5 py-2.5 text-sm font-semibold text-white">Save Payment</button><a href="fees.php" class="rounded-lg border px-5 py-2.5 text-sm font-semibold">Cancel</a></div></form>
<?php require __DIR__.'/includes/footer.php';?>
